---
abstract: 'Simple stringification of data.'
author:
  - 'Bob Kleemann <bobk@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Datify
requires:
  Carp: '0'
  List::Util: '0'
  Scalar::Util: '0'
  String::Tools: '0'
  overload: '0'
  perl: v5.14.0
  strict: '0'
  warnings: '0'
version: 0.14.133.1
